### PR TITLE
refactor: drop redundant config_status::pending_proposal

### PR DESCRIPTION
**Pull request by empiredan**
https://github.com/apache/incubator-pegasus/issues/908

### CODE REVIEW

**Comment by acelyc111** [comment]
Plz check whether `config_status` is appeared in RPC or disk storage, remove this state may cause incompatible problem.

**Comment by acelyc111** [comment]
I think mark an enum value as deprecated and remove all usage would be better.

**Comment by levy5307** [comment]
> Plz check whether `config_status` is appeared in RPC or disk storage, remove this state may cause incompatible problem.

+1

**Comment by hycdong** [comment]
> I think mark an enum value as deprecated and remove all usage would be better.

+1

**Comment by empiredan** [comment]
> > I think mark an enum value as deprecated and remove all usage would be better.
> 
> +1

Actually since pegasus v1.8 (or even older version) `pending_proposal` has not yet been used to assign any variable. It's only used to compare with some read operations rather than write to some variable. On the other hand, the only usage of it is to assign to `config_context::stage`, a variable in memory to record current state of the configuration of a partition which doesn't need to synced to disk.

However, in case of unexpected I think we'd better to mark it deprecated and remove all usages, without dropping the definitions.

**Review by levy5307 — APPROVED** [review]

**Review by acelyc111 — APPROVED** [review]

**Pull request merged**
