### PR TITLE
fix: fix replica::init_table_level_latency_counter metric name error

### PR DESCRIPTION
**Pull request by lidingshengHHU**
We should use taskcode(code).to_string() to get metric name , not taskcode(code) to get _internal_code.

### CODE REVIEW

**Comment by neverchanje** [comment]
Your code is not formatted. Please run clang-format-3.9 via `./scripts/linux/run-clang-format.sh`.

**Comment by lidingshengHHU** [comment]
> Your code is not formatted. Please run clang-format-3.9 via `./scripts/linux/run-clang-format.sh`.

**Comment by lidingshengHHU** [comment]
> Your code is not formatted. Please run clang-format-3.9 via `./scripts/linux/run-clang-format.sh`.

it's ok,now.

**Comment by lidingshengHHU** [comment]
> Your code is not formatted. Please run clang-format-3.9 via `./scripts/linux/run-clang-format.sh`.

it's ok,now. @neverchanje

**Comment by lidingshengHHU** [comment]
please check this pr，thanks @neverchanje

**Comment by neverchanje** [comment]
Sorry for late response. Since I've been busy dealing with my personal issues these days, I didn't have the time to check and test if your modication works. Would you pls add some tests result in the desctiption?

**Review by zhangyifan27 — APPROVED** [review]

**Comment by zhangyifan27** [comment]
I tested it and found that the output is same whether using `task_code(code)` or `task_code(code).to_string()`, and of course `task_code(code).to_string()` is more formal.

**Comment by lidingshengHHU** [comment]
> I tested it and found that the output is same whether using `task_code(code)` or `task_code(code).to_string()`, and of course `task_code(code).to_string()` is more formal.

But when I use task_code(code), the output is _internal_code. Do you know why?

**Comment by zhangyifan27** [comment]
> task_code(code)

I have no idea. I added a log:
```
ddebug_f("counter str is {} vs {}", task_code(code), task_code(code).to_string());
```
And it turned out the output is the same in both ways.

**Review by levy5307 — APPROVED** [review]

**Review by Shuo-Jia — APPROVED** [review]

**Comment by levy5307** [comment]
@lidingshengHHU Thanks for your pull request. Merged

**Pull request merged**
