### PR TITLE
fix: add app_info duplicating initial value

### PR DESCRIPTION
**Pull request by Arsenal821**

### CODE REVIEW

**Comment by Arsenal821** [comment]
from：https://github.com/apache/incubator-pegasus/issues/827

**Comment by Smityz** [comment]
It's strange give a optional parameter an initial value, can you fix it by another way?

**Comment by Shuo-Jia** [comment]
> from：[apache/incubator-pegasus#827](https://github.com/apache/incubator-pegasus/issues/827)

The reason is the thrift variable is `optional` so as to it won't be serialized into file.

**Comment by Arsenal821** [comment]
> It's strange to give an optional parameter an initial value, can you fix it in another way?

I don't think ignore this field different when we diff new app_info between old is better. And follow this field, is_bulk_loading also have an initial value. I have no idea for more.

**Review by hycdong — APPROVED** [review]

**Review by Shuo-Jia — APPROVED** [review]

**Review by levy5307 — APPROVED** [review]

**Pull request merged**
