### PR TITLE
lint: files under include/dsn/utility/ pass cpplint (Part 1)

### PR DESCRIPTION
**Pull request by neverchanje**
This PR fixes the warnings from cpplint for our wrong coding practice against google cpp code style, some of the warnings are listed as follows:

- Use int16/int64/etc, rather than the C type long  [runtime/int] 
```c
--    long get_count() const { return _counter.load(); }
++    int32_t get_count() const { return _counter.load(); }
```

- Namespace should be terminated with "// namespace dsn" [readability/namespace]
```c
-- }
++ } // namespace dsn
```

- Single-parameter constructors should be marked explicit.  [runtime/explicit]
```c
--    customized_id(const char *name);
++    explicit customized_id(const char *name);
```

- No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright]
```
++ /*
++ * The MIT License (MIT)
++ *
++ * Copyright (c) 2015 Microsoft Corporation
++ *
```

- Using C-style cast.  Use reinterpret_cast<void *>(...) instead  [readability/casting] 

```c
--    write((char *)&val, static_cast<int>(sizeof(T)));
++    write(reinterpret_cast<const char *>(&val), static_cast<int>(sizeof(T)));
```

- If an else has a brace on one side, it should have it on both  [readability/braces]
```c
              if (v2 == invalid_enum) {                                                              \
                  printf("invalid enum configuration '[%s] %s = %s'\n", section, #fld, v.c_str());   \
                  return false;                                                                      \
--            } else                                                                                 \
++            } else {                                                                               \
                  val.fld = v2;                                                                      \
++            }     
```

### CODE REVIEW

**Comment by shengofsun** [comment]
cpplint这件事我倒觉得不用这么急。比较重要的还是把模块间的耦合给拆清楚了：比如include/dsn/ci和include/dsn/cpp下面那几个头文件，该进utility的进utility，该进core的进core，也不要让utility依赖core的功能。

**Comment by neverchanje** [comment]
是啊，刚开始以为影响文件不多，结果lint才发现rdsn底下各种问题

**Comment by shengofsun** [comment]
感觉依赖的第三方库都用""不太好啊

**Comment by neverchanje** [comment]
@shengofsun tensorflow 也是这么干的，baidu/apollo 也是这么干的，目前看用了 cpplint 但不这么干的只有 kudu，因为它把 -build/include_order 给禁了。
改成 "" 是因为 cpplint 认为 `<gtest/gtest.h>` 这个可能是一个 c 系统库的头文件，它没办法判断这是 c 系统库还是 c++ thirdparty 因为都是 .h 结尾，如果是 c 系统库就要放在头文件最上面，跟 unistd.h 这种放在一起，这个肯定是违背 include-order 这个规则的初衷的
build/include_order 这个如果禁掉我们就要自觉保持规范，我觉得挺难的

**Comment by qinzuoyan** [comment]
这个pr节最近先不提交，先保证稳定性

**Pull request closed without merging**
